[[redirects]]
  from = "/pleinAir"
  to = "/pleinAir"
  status = 200
  force = true

[[redirects]]
  from = "/illustration"
  to = "/illustration"
  status = 200
  force = true

[[redirects]]
  from = "/login"
  to = "/login"
  status = 200
  force = true

[[redirects]]
  from = "/locked"
  to = "/locked"
  status = 200
  force = true

[[redirects]]
  from = "/about"
  to = "/about"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
