[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

  [[redirects]]
  from = "/pleinAir"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/illustration"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/locked"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/portfolio"
  to = "/index.html"
  status = 200